const SECOND_MS = 1000;
const MINUTE_SECONDS = 60;
const MINUTE_MS = MINUTE_SECONDS * SECOND_MS;
const HOUR_MS = 60 * MINUTE_MS;
const DAY_MS = 24 * HOUR_MS;

export const TTL_MS = {
  EMAIL_VERIFICATION: DAY_MS,
  PASSWORD_RESET: 30 * MINUTE_MS,
  SMS_CODE: 5 * MINUTE_MS,
  REFRESH_SESSION: 30 * DAY_MS,
  STAFF_INVITE: 7 * DAY_MS,
} as const;

export const TTL_SECONDS = {
  ACCESS_TOKEN: 15 * MINUTE_SECONDS,
} as const;
